baseURL = "" #ä½ çš„ç½‘å€,ä»¥æ–œæ  / ç»“å°¾
languageCode = "zh-CN"
title = "Marx's Favourite" #ç½‘ç«™åç§°
theme = "bluf"

[params]
  pagename = "Marx's Favourite" #é¦–é¡µæ ‡é¢˜
  description = "Marxçš„ç§äººç½‘ç»œåšç‰©é¦†" #SEOï¼Œä½ çš„ç½‘ç«™æè¿°
  keywords = [
  "ç‹¼é›†",
  "Wolf Set",
  "ç‹¼ç‰Œ",
  "ç‹¼ç‰Œå·¥ä½œç½‘å€å¯¼èˆª",
  "ç½‘å€å¤§å…¨",
  "ç½‘å€ä¹‹å®¶",
  "ç½‘å€å¯¼èˆª",
  "è®¾è®¡å·¥å…·",
  "Markdownèµ„æº",
  "åŠå…¬è½¯ä»¶",
  "å®‰å…¨å·¥å…·",
  "All in One"
] #SEOï¼Œç½‘ç«™å…³é”®è¯
  author = "Marx" #SEOï¼Œç½‘ç«™ä½œè€…
  alias ="Marxç½‘å€å¯¼èˆª" #SEOï¼Œå¯åˆ é™¤
  #license="CC BY-NC 4.0" #ç½‘ç«™æˆæƒä¿¡æ¯ï¼Œhttps://chooser-beta.creativecommons.org/

  # enableUmami = False #umami ç»Ÿè®¡ç›¸å…³ï¼Œæ²¡æœ‰è¯· falseï¼Œhttps://umami.is/
  # UmamiLink = "https://eu.umami.is/script.js"
  # UmamiID = "02cc419c-d758-4a4f-a9bd-1e442b1f8435"

  lightColor = "#0000cd" # æµ…è‰²å¼ºè°ƒè‰²ï¼Œæ¨èè¾ƒæ·±
  darkColor = "#fafafa" # æ·±è‰²å¼ºè°ƒè‰²ï¼Œæ¨èè¾ƒæµ…

  gallery = true #å¯ç”¨ç”»å»Šæ¨¡å¼

  greetings = [
    "ä½ å¥½æœ‹å‹ï¼Œä½ å¥½ä¸–ç•Œ ğŸ‰",
    "å—·~ è®°å¾—æ—©ç‚¹ä¼‘æ¯ ğŸŒ›",
    "äº’è”ç½‘ç¬¬ä¸€æ¡æ¶ˆæ¯æ˜¯ LO ğŸ’¡",
    "äº’è”ç½‘é‡é‡æˆ–æ˜¯ä¸€é¢—è‰è“ ğŸ’¡",
    "äº’è”ç½‘ç¬¬ä¸€ä¸ªè¡¨æƒ…æ˜¯:-) ğŸ’¡",
    "Ctrl+F æœç´¢æœ¬ç«™ ğŸ”",
    "Ctrl+D æ”¶è—æœ¬ç«™ â­",
    "ç‚¹å‡»ã€æ ‡ç­¾ã€‘ï¼Œç­›é€‰å†…å®¹ ğŸ”–",
    "ç‚¹å‡» â—ï¼Œåˆ‡æ¢æ·±æµ…é…è‰² ğŸ¼",
] #è®¿å®¢éšæœºé—®å€™ï¼Œä¸ºç©ºä¸å¯ç”¨
  mobileGreetings = [
    "æ¨èç”µè„‘è®¿é—®ï¼Œä½“éªŒæ›´ä½³ ğŸ’»",
] #ç§»åŠ¨ç«¯è®¿å®¢éšæœºé—®å€™ï¼Œä¸ºç©ºä½¿ç”¨ greetings

confettiEmojis = [ 'ğŸ¥Ÿ', 'ğŸœ', 'ğŸŠ', 'ğŸ§§', 'ğŸ§¨', 'ğŸ®', 'ğŸ‰', 'ğŸº' ] # æ¸…é™¤ç­›é€‰æ—¶æ’’èŠ±ï¼Œä¸ºç©ºä¸å¯ç”¨
  

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]
  
[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"


[markup]
[markup.highlight]
    style = "gruvbox"

[minify]
  minifyOutput = true
