baseURL = 'https://ws.0000cd.com/'
languageCode = 'zh-CN'
title = 'ç‹¼ç‰Œç½‘å€å¯¼èˆª - ç‹¼é›† Wolf Set'
theme = 'bluf'

[params]
  description = " ç‹¼é›† Wolf Set, æºè‡ªâ€œç‹¼ç‰Œå·¥ä½œç½‘å€å¯¼èˆªâ€ï¼Œé›†è®¾è®¡ã€Markdownã€è½¯ä»¶ã€å®‰å…¨ã€åŠå…¬å¿…å¤‡ç½‘å€äºä¸€ä½“ï¼ŒAll in One æœ€ä½³é€‰æ‹©ã€‚"
  keywords = [
  "ç‹¼é›†",
  "Wolf Set",
  "ç‹¼ç‰Œ",
  "ç‹¼ç‰Œå·¥ä½œç½‘å€å¯¼èˆª",
  "ç½‘å€å¤§å…¨",
  "ç½‘å€ä¹‹å®¶",
  "ç½‘å€å¯¼èˆª",
  "è®¾è®¡å·¥å…·",
  "Markdownèµ„æº",
  "åŠå…¬è½¯ä»¶",
  "å®‰å…¨å·¥å…·",
  "All in One"
]
  author = "0000CD.COM & é€Šç‹¼"
  pagename = "ç‹¼é›† Wolf Set"
  alias ="ç‹¼ç‰Œç½‘å€å¯¼èˆª"
  license="CC BY-NC 4.0"

  enableUmami = true
  UmamiLink = "https://eu.umami.is/script.js"
  UmamiID = "02cc419c-d758-4a4f-a9bd-1e442b1f8435"

  greetings = [
    "ä½ å¥½æœ‹å‹ï¼Œä½ å¥½ä¸–ç•Œ ğŸ‰",
    "ä¸Šç½‘å†²æµªå°±æ˜¯å¿« ğŸŒŠ",
    "å—·~ è®°å¾—æ—©ç‚¹ä¼‘æ¯ ğŸº",
    "Ctrl+F æœç´¢æœ¬ç«™ ğŸ”",
    "Ctrl+D æ”¶è—æœ¬ç«™ â­",
    "ç‚¹å‡»ã€æ ‡ç­¾ã€‘ï¼Œç­›é€‰å†…å®¹ ğŸ”–",
    "ç‚¹å‡» â—ï¼Œåˆ‡æ¢æ·±æµ…é…è‰² ğŸ¼",
]
  

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]
  
[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"


[markup]
[markup.highlight]
    style = 'gruvbox'

[minify]
  minifyOutput = true